FROM docker.io/debian:sid

RUN apt-get update
RUN apt-get install -y build-essential file curl gawk bison python3 pkg-config
# RUN apt-get install -y libgmp-dev libmpfr-dev libmpc-dev zlib1g-dev
# RUN apt-get install -y libattr1-dev libacl1-dev
# RUN apt-get install -y libncurses-dev
RUN ldconfig
