---
layers: ["base"]
package:
  stages:
    build:
      script: |
        test -n "$USE_BUILDDIR" && cd build
        make V=1 -j$X10_MAKE_JOBS
    install:
      script: |
        test -n "$USE_BUILDDIR" && cd build
        make DESTDIR="$DESTDIR" install
