---
layers: ["base"]
package:
  stages:
    build:
      script: |
        test -n "$USE_BUILDDIR" && cd build
        make V=1 -j$X10_MAKE_JOBS
    test:
      script: |
        test -n "$USE_BUILDDIR" && cd build
        test -n "$SKIP_TESTS" && exit 0
        if make -q ${CHECK_TARGET:-check} 2>/dev/null; then
          :
        else
          if [ $? -eq 2 ]; then
            exit 0
          fi
        fi

        make V=1 -j$X10_MAKE_JOBS ${CHECK_TARGET:-check}
    install:
      script: |
        test -n "$USE_BUILDDIR" && cd build
        make DESTDIR="$DESTDIR" install
