#!/usr/bin/env bash

set -e

# cd $(dirname $1)
# bash -ec "source $(basename $1); x10-run \$@" "$@"

if [ -z "$X10" ]; then
    rm -rf /tmp/x10_cache
    mkdir -p /tmp/x10_cache
    export -p > /tmp/x10_env
fi

export X10=$(realpath $0)
export X10_SRC=$(realpath $1)
shift

# echo "$1 $X10_SRC" >&2

cd $(dirname $X10_SRC)
if [ "$1" = "generate" ]; then
    if [ ! -e /x10/buildscripts/$($X10 $X10_SRC hash).sh ]; then
        for src in $($X10 $X10_SRC _recurse_srcs | sort | uniq) "$X10_SRC"; do
            src_hash=$($X10 $src hash)
            bash -ec "source $src; X10_CURRENT_SRC=$src _generate" >/x10/buildscripts/${src_hash}.sh.tmp
            mv /x10/buildscripts/${src_hash}.sh{.tmp,}
            echo '  => generated:' /x10/buildscripts/${src_hash}.sh
        done
    fi
elif [ "$1" = "build" ]; then
    $X10 $X10_SRC generate
    sh /x10/buildscripts/$($X10 $X10_SRC hash).sh
elif [ "$1" = "hash" ]; then
    if [ ! -e /tmp/x10_cache/hash-$(basename $X10_SRC) ]; then
        echo "  => cache miss: hash $(basename $X10_SRC)" >&2
        echo $(bash -ec "source $X10_SRC; X10_CURRENT_SRC=$X10_SRC _generate | sha256sum | head -c7")-$(bash -ec 'source $X10_SRC; echo $PACKAGE-$VERSION') >/tmp/x10_cache/hash-$(basename $X10_SRC)
    fi
    cat /tmp/x10_cache/hash-$(basename $X10_SRC)
elif [ "$1" = "_get_srcs" ]; then
    if [ ! -e /tmp/x10_cache/srcs-$(basename $X10_SRC) ]; then
        echo "  => cache miss: srcs $(basename $X10_SRC)" >&2
        bash -ec "source $X10_SRC; X10_CURRENT_SRC=$X10_SRC _generate >/dev/null; echo \$X10_IMPORTED" >/tmp/x10_cache/srcs-$(basename $X10_SRC)
    fi
    cat /tmp/x10_cache/srcs-$(basename $X10_SRC)
elif [ "$1" = "_recurse_srcs" ]; then
    if [ ! -e /tmp/x10_cache/allsrcs-$(basename $X10_SRC) ]; then
        export X10_ALREADY_IMPORTED="$X10_SRC $X10_ALREADY_IMPORTED"
        for depend_src in $($X10 $X10_SRC _get_srcs); do
            if [[ ! $X10_ALREADY_IMPORTED == *"$depend_src"* ]]; then
                echo "${depend_src}"
                export X10_ALREADY_IMPORTED="$depend_src $X10_ALREADY_IMPORTED"
                $X10 $depend_src _recurse_srcs
            fi
        done | sort -u > /tmp/x10_cache/allsrcs-$(basename $X10_SRC)
    fi
    cat /tmp/x10_cache/allsrcs-$(basename $X10_SRC)
elif [ "$1" = "_source_date_epoch" ]; then
    if [ -n "$(git log -1 --pretty=%ct $X10_SRC)" ] && git diff --exit-code "$X10_SRC" >/dev/null; then
        # git version is latest so its timestamp is OK
        echo $(git log -1 --pretty=%ct $X10_SRC)
    else
        # file either hasn't been committed or has been modified locally, use its modification time
        echo $(stat -c%Y $X10_SRC)
    fi
elif [ "$1" = "_int_package" ]; then
    mkdir -p $(dirname $X10)/builtpkgs
    $X10 $X10_SRC generate
    if [ ! -e /x10/tree/$($X10 $X10_SRC hash) ]; then
        $X10 $X10_SRC build
    fi

    for src in "$X10_SRC" $($X10 $X10_SRC _recurse_srcs | sort -u); do
        src_hash=$($X10 $src hash)
        bash -ec "source $src; X10_CURRENT_SRC=$src _generate" >/x10/buildscripts/${src_hash}.sh
        echo /x10/buildscripts/${src_hash}.sh
    done | xargs tar --sort=name --mtime="@$($X10 $X10_SRC _source_date_epoch)" --owner=0 --group=0 --numeric-owner --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
        -czf $(dirname $X10)/builtpkgs/$($X10 $X10_SRC hash).scripts.tar.gz.tmp
    tar --sort=name --mtime="@$($X10 $X10_SRC _source_date_epoch)" --owner=0 --group=0 --numeric-owner --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
        -czf $(dirname $X10)/builtpkgs/$($X10 $X10_SRC hash).tar.gz.tmp /x10/tree/$($X10 $X10_SRC hash)
    mv $(dirname $X10)/builtpkgs/$($X10 $X10_SRC hash).scripts.tar.gz{.tmp,}
    mv $(dirname $X10)/builtpkgs/$($X10 $X10_SRC hash).tar.gz{.tmp,}
    echo $(dirname $X10)/builtpkgs/$($X10 $X10_SRC hash){,.scripts}.tar.gz
elif [ "$1" = "package" ]; then
    for src in $X10_SRC $($X10 $X10_SRC _recurse_srcs | sort -u); do
        if [ ! -e $(dirname $X10)/builtpkgs/$($X10 $src hash).tar.gz ]; then
            $X10 $src _int_package
        fi
    done
elif [ "$1" = "get_path" ]; then
    bash -ec "unset PATH; source $(dirname $X10)/lib.sh; _do_import $($X10 $X10_SRC hash); echo PATH=\"\$PATH\""
elif [ "$1" = "latest" ]; then
    # find the file-list with the newest timestamp (because it should always be equal to SOURCE_DATE_EPOCH)
    ls -rt /x10/tree/*/file-list | egrep '[0-9a-f]+-'$(basename $X10_SRC)'-[0-9]([[:alnum:].])+/file-list$' | tail | xargs dirname | xargs basename
fi
