#!/bin/bash

PKGDIR="/var/db/rpkg"
if [ -z "$MAKEOPTS" ]; then
    export MAKEOPTS=-j56
fi

# TODO need to split to proper host-install-dir and target-install-dir or whatever
# but then I need to actually make bdeps function properly
declare ADDITIONAL_INSTALL_DIR
declare ASSUME_EMPTY_TREE

declare -A selected

file_to_atom() {
    local file=$1

    dirname=$(dirname $(dirname $file))
    file=${file#$dirname}
    file=${file#/}
    file=${file%.sh}
    file=${file%.tar.xz}
    echo $file
}

atom_to_build() {
    local atom=$1

    echo $PKGDIR/built/$atom.tar.xz
}

atom_to_package() {
    local atom=$1

    echo $PKGDIR/packages/$atom.sh
}

name_part() {
    local atom=$1

    atom=${atom%@*}
    atom=${atom%^*}
    echo $atom
}

is_atom() {
    local atom=$1 

    local d=$(expr $atom : '.*/.*@.*')
    return $?
}

version_part() {
    local specifier=$1
    local single_version=$(expr "$specifier" : '.*@\(.*\)')
    local ge_version=$(expr "$specifier" : '.*^\(.*\)')
    if [ -n "$single_version" ]; then
        echo '@'$single_version
    else
        echo '^'$ge_version
    fi
}

versions_compatible() {
    local v1=$1
    local v2=$2

    if [ -z "$v1" ]; then
        return true
    elif [[ "$v1" = @* ]]; then
        [ "$v1" = "$v2" ]
        return $?
    elif [[ "$v1" = ^* ]]; then
        local ge_version=$(expr "$v1" : '.*^\(.*\)')
        local single_version=$(expr "$v2" : '.*@\(.*\)')
        [[ ! ( $single_version < $ge_version ) ]]
        return $?
    else
        echo -e "\e[31mBad version string '$v1'"
        exit 1
    fi
}

find_installation_candidate() {
    local specifier=$1  

    local pkgver=$(version_part $specifier)
    local pkgname=$(name_part $specifier)

    declare -A names
    local sel

    if [ -d $PKGDIR/installed ]; then
        INSTALLED=$(find $PKGDIR/installed | grep "$pkgname@")
        for cand in $INSTALLED; do
            local atom=$(file_to_atom $cand)
            local name=$(name_part $atom)
            local version=$(version_part $atom)

            if versions_compatible $pkgver $version \
                && [ -z "$ASSUME_EMPTY_TREE" ] \
                && [ $name = $pkgname ]; then
                echo "installed"
                return 0
            fi
        done
    fi

    CANDIDATES=$(find $PKGDIR/packages | grep "$pkgname@")
    for cand in $CANDIDATES; do
        local atom=$(file_to_atom $cand)
        local name=$(name_part $atom)
        local version=$(version_part $atom)

        if versions_compatible $pkgver $version \
            && [ -z "${names[$name]}" -o "${names[$name]}" '<' "$version" ]; then
            names[$name]=$version
            sel=$name
        fi

    done

    if [ ${#names[@]} -eq 0 ]; then
        echo -e "\e[31mNo package found for $specifier\e[0m" >&2
        exit 1
    elif [ ${#names[@]} -gt 1 ]; then
        echo -e "\e[31mMultiple packages found for $specifier: \e[0m" >&2
        for k in "${!names[@]}"; do
            echo "    => $k" >&2
        done
        exit 1
    fi

    sel="${sel}${names[$sel]}"

    unset names
    declare -A names

    BUILT=$(find $PKGDIR/built | grep $sel)
    for cand in $BUILT; do
        local atom=$(file_to_atom $cand)
        local name=$(name_part $atom)
        local version=$(version_part $atom)

        if versions_compatible $pkgver $version \
            && [ -z "${names[$name]}" -o "${names[$name]}" '<' "$version" ]; then
            names[$name]=$version
        fi
    done

    if [ ${#names[@]} -gt 0 ]; then
        sel=$(name_part $sel)
        echo $(atom_to_build ${sel}${names[$sel]})
    else
        echo $(atom_to_package $sel)
    fi
}

select_depends() {
    local package=$1

    if [ -n "${selected[$(name_part $package)]}" ]; then
        return 0
    fi

    cand=$(find_installation_candidate $package)
    atom=$(file_to_atom $cand)

    if [ "$cand" = "installed" ]; then
        cand=$(ASSUME_EMPTY_TREE=1 find_installation_candidate $package)
        atom=$(file_to_atom $cand)
        selected[$(name_part $atom)]="installed"
        return 0
    fi

    selected[$(name_part $atom)]=$cand

    declare depends

    if [[ $cand = *.sh ]]; then
        # Building from source, so we need bdeps as well
        depends=$(bash -c "source /var/lib/rpkg/mod/base.sh; source $cand; echo \$BDEPEND")
    fi

    local rdepend=$(bash -c "source /var/lib/rpkg/mod/base.sh; source $(atom_to_package $atom); echo \$RDEPEND")
    depends="$depends $rdepend" 

    for depend in $depends; do select_depends $depend; done
}

debug_selected() {
    for k in "${!selected[@]}"; do
        echo "$k" '=>' ${selected[$k]}
    done
}

do_ldconfig() {
    echo "Running ldconfig (system)"
    ldconfig -X
    if [ -n "$ADDITIONAL_INSTALL_DIR" ]; then
        ldconfig -X -r "$ADDITIONAL_INSTALL_DIR"
    fi

    # TODO figure out why ldconfig doesn't figure this crap out on its own
    if [[ ! -e /lib64/ld-linux-x86-64.so.2 ]]; then
        ln -s $(readlink /lib/ld-linux-x86-64.so.2) /lib64/ld-linux-x86-64.so.2
    fi
    unset NEED_LDCONFIG
}

mark_installed() {
    atom=$1

    mkdir -p $(dirname "$PKGDIR/installed/$atom")
    touch "$PKGDIR/installed/$atom"
    if [ -n "$ADDITIONAL_INSTALL_DIR" ]; then
    mkdir -p $(dirname "$ADDITIONAL_INSTALL_DIR/var/db/rpkg/installed/$atom")
        touch "$ADDITIONAL_INSTALL_DIR/var/db/rpkg/installed/$atom"
    fi
}

install_from_build() {
    atom=$1
    build=$(atom_to_build $atom)

    tarfile=${atom//\//_}.tar
    if [ -d /tmp ]; then
        if [ -e /usr/bin/pv ]; then
            pv -peb -N "$atom" <"$build" | xz -dc - >"/tmp/$tarfile"
        else
            echo "[-------- Installing: $atom --------]"
            xz -dc "$build" >"/tmp/$tarfile"
        fi
        bash -c "cd /; tar xpf /tmp/$tarfile"
        if tar tvf "/tmp/$tarfile" | fgrep -q -e lib/ -e usr/lib/; then
            NEED_LDCONFIG=1
        fi
        if [ -n "$ADDITIONAL_INSTALL_DIR" ]; then
            bash -c "cd $ADDITIONAL_INSTALL_DIR; tar xpf /tmp/$tarfile"
        fi
        rm "/tmp/$tarfile"
    else
        echo "[-------- Installing: $atom --------]"
        bash -c "cd /; tar xpfJ $build"
        if [ -n "$ADDITIONAL_INSTALL_DIR" ]; then
            bash -c "cd $ADDITIONAL_INSTALL_DIR; tar xpfJ $build"
        fi
    fi

    mark_installed $atom
}

do_package_checks() {
    pkgsrc=$1

    if [[ -z $(bash -c "source /var/lib/rpkg/mod/base.sh; source '$pkgsrc'; echo \$SRC_URL") ]]; then
        echo -e "\e[33m$(file_to_atom $pkgsrc) does not define a SRC_URL - this will cause problems later\e[0m"
    fi
}

build_one_selected() {
    local pkg=$1

    local pkgsrc=${selected[$pkg]}
    echo "pkgsrc=$pkgsrc" >&2
    local atom=$(file_to_atom $pkgsrc)
    #bash -exc "source /var/lib/rpkg/mod/base.sh; source '$pkgsrc'; type -t pkg_build" || exit 1
    do_package_checks $pkgsrc

    if [ "$(bash -c "source /var/lib/rpkg/mod/base.sh; source '$pkgsrc'; type -t pkg_build")" = 'function' ]; then
        echo "[-------- Building from source: $pkg --------]"
        if [ -n "$NEED_LDCONFIG" ]; then
            do_ldconfig
        fi
        local dist_src=$(bash -c "source /var/lib/rpkg/mod/base.sh; source $pkgsrc; echo \$SRC")
        if [ -n "$dist_src" ]; then
            for f in $dist_src; do
                if [ ! -e "$PKGDIR/distfiles/$f" ]; then
                    echo -e "\e[31mCan't find $df for $pkg!\e[0m"
                    exit 1
                fi
            done
        fi

        rm -rf "/tmp/build-$pkg"
        mkdir -p "/tmp/build-$pkg"
        if [ -n "$dist_src" ]; then
            for f in $dist_src; do
                cp "$PKGDIR/distfiles/$f" "/tmp/build-$pkg"
            done
        fi

        if bash -c "cd '/tmp/build-$pkg'; source /var/lib/rpkg/mod/base.sh; source '$pkgsrc'; set -e; pkg_build"; then
            mkdir -p $(dirname $(atom_to_build $atom))
            echo "Compressing package for $atom"
            bash -c "cd '/tmp/build-$pkg'; tar cp . | xz -T 0 > '$(atom_to_build $atom)'"
            install_from_build $atom
        else
            echo -e "\e[31mSomething went wrong while building $pkg. Stopping."
            exit 1
        fi
    else 
        mark_installed $atom
    fi
}

build_recursive() {
    local atom=$1
    local pkg=$(name_part $atom)
    local pkgsrc=${selected[$pkg]}

    echo "BUILD_RECURSIVE $atom"

    local d=$(expr $atom : '.*/.*@.*')
    [ "$d" -ne 0 ] || {
        echo -e "\e[31mbuild_recursive was passed $atom, which does not specify a single package\e[0m"
        echo -e "\e[31mthis is a bug in rpkg or in a package depending on $atom\e[0m"
        exit 1
    }   

    if [ ! -e "$PKGDIR/installed/$atom" ]; then
        local depends=$(bash -c "source /var/lib/rpkg/mod/base.sh; source $pkgsrc; echo \$BDEPEND \$RDEPEND")
        for depend in $depends; do
            if [[ ${selected[$(name_part $depend)]} = *.sh ]]; then
                echo "building $depend for $atom"
                build_recursive $(file_to_atom ${selected[$(name_part $depend)]})
            fi
        done
        build_one_selected $pkg
    else
	    echo "$atom is already installed"
    fi
}

build() {
    local package=$1

    select_depends $package

    local to_install=""
    local to_build=""

    for k in "${!selected[@]}"; do
        if [[ ${selected[$k]} = "installed" ]]; then
            echo -e "$k \e[32mis already installed\e[0m"
        elif [[ ${selected[$k]} = *.tar.xz ]]; then
            echo -e "$k \e[33mis available locally\e[0m"
            to_install="$to_install $k"
        elif [[ ${selected[$k]} = *.sh ]]; then
            echo -e "$k \e[31mmust be built from source\e[0m"
            to_build="$to_build $k"
        else
            echo -e "$k \e[35mis $selected[$k] (shouldn't happen)\e[0m"
        fi
    done

    for pkg in $to_install; do
        install_from_build $(file_to_atom ${selected[$pkg]})
    done

    local cand=$(find_installation_candidate $package)
    local atom=$(file_to_atom $cand)
    local pkgname=$(name_part $atom)

    for k in "${!selected[@]}"; do
        if [[ ${selected[$k]} = *.sh ]]; then
            build_recursive $(file_to_atom ${selected[$k]})
        fi
    done

    if [ -n "$NEED_LDCONFIG" ]; then
        do_ldconfig
    fi
}

PARAMS=""

while (( "$#" )); do
    case "$1" in
        --pkgdir=*)
            arg=$1
            PKGDIR=$(realpath $(expr "$arg" : '.*=\(.*\)'))
            shift
            ;;
        --additional-install-dir=*)
            arg=$1
            ADDITIONAL_INSTALL_DIR=$(realpath $(expr "$arg" : '.*=\(.*\)'))
            ASSUME_EMPTY_TREE=1
            shift
            ;;
        -*|--*=)
            echo "unknown argument: $1"
            exit 1
            ;;
        *)
            PARAMS="$PARAMS $1"
            shift
            ;;
    esac
done

eval set -- "$PARAMS"

case "$1" in
    build)
        build $2
        ;;
    build-without-depends)
        package=$2
        cand=$(find_installation_candidate $package)
        atom=$(file_to_atom $cand)
        if [[ $cand = *.sh ]]; then
            selected[$(name_part $atom)]=$cand
            echo "Building: $atom $cand"

            build_one_selected $(name_part $atom)
        elif [[ $cand = *.tar.xz ]]; then
            install_from_build $atom
        fi
        if [ -n "$NEED_LDCONFIG" ]; then
            do_ldconfig
        fi
        ;;
    *)
        echo "unknown subcommand $1"
        exit 1
        ;;
esac
